### ISSUE TITLE
error on clicking trim file after selecting the audio file

### ISSUE THREAD

**Issue by shabaad** [vvvirani/audio_cutter#1]
I/flutter ( 3277): MissingPluginException(No implementation found for method trim on channel vvvirani/flutter_audio_trimmer)

**Comment by vvvirani** [comment]
Ok i will check and update you.

**Comment by shabaad** [comment]
Now shows "lateinit property ffmpeg has not been initialized" in snackbar after selecting file and clicking trim audio

screenshot :
![ac163028-3d9a-4bd5-9d86-a67eec71bad1](https://user-images.githubusercontent.com/105212229/232460547-20346a99-c1b2-40bc-b89d-3e9273bdaaf1.jpg)

**Comment by vvvirani** [comment]
Are you using the latest version ?

**Comment by vvvirani** [comment]
Hello, I have fixed error

User flutter_audio_trimmer 0.0.4 version

**Comment by shabaad** [comment]
Used latest version 0.0.4 but showing invalid arguments in snackbar...
Also checked with different device 
Error : 
D/FFmpeg  ( 9829): Build.CPU_ABI : arm64-v8a
I/FFmpeg  ( 9829): Loading FFmpeg for armv7 CPU
W/com.example.flutter_application_1222( 9829): type=1400 audit(0.0:95590): avc: granted { execute } for comm=4173796E635461736B202331 name="ffmpeg" dev="dm-9" ino=185655 scontext=u:r:untrusted_app:s0:c171,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c171,c257,c512,c768 tclass=file app=com.example.flutter_application_1222
E/FFmpeg  ( 9829): Exception while trying to run: [Ljava.lang.String;@e8c145c
E/FFmpeg  ( 9829): java.io.IOException: Cannot run program "/data/user/0/com.example.flutter_application_1222/files/ffmpeg": error=13, Permission denied
E/FFmpeg  ( 9829): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
![photo_6192986384772478194_y](https://user-images.githubusercontent.com/105212229/232675277-83610a5b-a528-4fcd-823b-7c6983ee1664.jpg)
