### ISSUE TITLE
Trimming timing too restrictive

### ISSUE THREAD

**Issue by SebasRebazCoding** [vvvirani/audio_cutter#4]
I am currently using this package to trim audio files, but when I set the start too close to the audio's actual beginning, it throws an exception saying the following in a more technical fashion: The start and end Durations in Seconds cannot be zero.

This doesn't work very well when trying to trim content near the start or the end of an audio. Most online audio editors allow the user to trim a file with a precision down to the hundredth of a second. I suggest changing the assertion method from ".inSeconds" to ".inMilliseconds".
![imagen_2024-07-08_174951461](https://github.com/vvvirani/flutter_audio_trimmer/assets/106042033/50b1693f-1806-4c8f-8f4b-a67997e14a92)

**Comment by vvvirani** [comment]
Hello @SebasRebazCoding It's supported for only seconds

**Comment by SebasRebazCoding** [comment]
I see. Thank you for your response.
